# Generated by Django 4.2.4 on 2023-09-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
    ]
