# Generated by Django 4.2.4 on 2023-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_profile_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
