# Generated by Django 3.2.18 on 2023-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(upload_to='hotel_gallery'),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='image',
            field=models.FileField(upload_to='hotel_gallery'),
        ),
    ]
