# Generated by Django 3.2.18 on 2023-07-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20230731_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelfaqs',
            options={'verbose_name_plural': 'Hotel FAQs'},
        ),
        migrations.AlterModelOptions(
            name='hotelfeatures',
            options={'verbose_name_plural': 'Hotel Features'},
        ),
        migrations.AlterModelOptions(
            name='hotelgallery',
            options={'verbose_name_plural': 'Hotel Gallery'},
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('King', 'King'), ('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic')], max_length=50),
        ),
    ]
