# Generated by Django 3.2.18 on 2023-07-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
