# Generated by Django 3.2.18 on 2023-07-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number_of_beds',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
