# Generated by Django 4.2.2 on 2023-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_tracker',
            field=models.BooleanField(default=False, help_text='DO NOT CHECK THIS BOX'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out_tracker',
            field=models.BooleanField(default=False, help_text='DO NOT CHECK THIS BOX'),
        ),
    ]
